import { Link } from "react-router-dom";
import { HeartHandshake } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";

const sections = [
  { he: ["מחויבות לנגישות", "מُلتقى מחויבת להנגשת האתר לאנשים עם מוגבלות, בהתאם לחוק שוויון זכויות לאנשים עם מוגבלות (תיקוני חקיקה), התשנ\"ח-1998, ולתקנות שהותקנו מכוחו. המטרה היא לאפשר לכל אדם, לרבות אנשים עם מוגבלות, להשתמש באתר באופן עצמאי ושוויוני."], ar: ["الالتزام بإمكانية الوصول", "تلتزم مُلتقى بجعل الموقع متاحًا للأشخاص ذوي الإعاقة، وفقًا لقانون مساواة الحقوق للأشخاص ذوي الإعاقة (تعديلات تشريعية) لعام 1998، واللوائح الصادرة بموجبه. والهدف هو تمكين كل شخص، بما في ذلك ذوو الإعاقة، من استخدام الموقع بشكل مستقل ومتساوٍ."] },
  { he: ["רמת הנגישות", "האתר מונגש ברמת AA לפי הנחיות WCAG 2.1 של ארגון W3C. הנגשה זו כוללת ניגודיות צבעים נאותה, ניווט במקלדת, טקסט חלופי לתמונות, תוויות נגישות לטפסים ומבנה סמנטי תקין."], ar: ["مستوى إمكانية الوصول", "يُوفَّر الموقع بمستوى AA وفق إرشادات WCAG 2.1 الصادرة عن منظمة W3C. تشمل إمكانية الوصول هذه تباينًا لونيًا مناسبًا، وتصفحًا بلوحة المفاتيح، ونصًا بديلًا للصور، وتسميات وصول للنماذج، وبنية دلالية سليمة."] },
  { he: ["התאמות שבוצעו", "בוצעו התאמות נגישות מגוונות, לרבות קישור דילוג לתוכן הראשי, סימון אייקונים דקורטיביים, תוויות לכל שדה בטפסים, אזורי הודעות נגישים לעדכונים דינמיים, וכיבוד העדפת תנועה מופחתת."], ar: ["التسهيلات المنفذة", "تم تنفيذ تسهيلات وصول متعددة، بما في ذلك رابط تخطٍّ إلى المحتوى الرئيسي، ووضع علامات على الرموز الزخرفية، وتسميات لكل حقل في النماذج، ومناطق رسائل متاحة للتحديثات الديناميكية، واحترام تفضيل تقليل الحركة."] },
  { he: ["מגבלות ידועות", "למרות המאמצים, ייתכן שחלק מהעמודים או הרכיבים אינם מונגשים במלואם. אם נתקלת בקושי או בליקוי נגישות, נשמח שתיידע אותנו ונפעל לתיקון."], ar: ["قيود معروفة", "على الرغم من الجهود، قد لا تكون بعض الصفحات أو المكوّنات متاحة بالكامل. إذا واجهت صعوبة أو مشكلة في الوصول، يُرجى إعلامنا وسنعمل على معالجتها."] },
  { he: ["יצירת קשר לענייני נגישות", "לדיווח על בעיית נגישות או לבקשת סיוע, ניתן לפנות אלינו דרך טופס יצירת הקשר באתר או באמצעות פרטי הקשר המפורסמים. נשתדל להגיב בהקדם."], ar: ["التواصل بشأن إمكانية الوصول", "للإبلاغ عن مشكلة وصول أو طلب المساعدة، يمكن التواصل معنا عبر نموذج التواصل في الموقع أو من خلال بيانات الاتصال المنشورة. سنبذل للرد في أقرب وقت."] },
  { he: ["עדכון ההצהרה", "הצהרה זו תתעדכן מעת לעת בהתאם לשיפורים ולהתאמות שייעשו באתר. תאריך העדכון האחרון מופיע להלן."], ar: ["تحديث البيان", "سيتم تحديث هذا البيان من حين لآخر وفقًا للتحسينات والتعديلات التي تُجرى على الموقع. يظهر تاريخ آخر تحديث أدناه."] },
];

export default function Accessibility() {
  return <main id="main-content" dir="rtl" className="min-h-screen bg-background"><header className="border-b bg-card"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link to="/" className="flex items-center gap-2 font-heading text-xl font-semibold"><HeartHandshake className="h-6 w-6" />مُلتقى</Link><Link to="/" className="text-sm font-medium text-primary underline">חזרה למאגר</Link></div></header><article className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm font-medium text-primary">עדכון אחרון: 8 בספטמבר 2026</p><h1 className="mt-2 font-heading text-4xl font-semibold text-foreground">הצהרת נגישות | إمكانية الوصول</h1><p className="mt-5 leading-8 text-muted-foreground">הצהרה זו מתארת את מחויבות מُلتقى לנגישות בהתאם לחוק שוויון זכויות לאנשים עם מוגבלות.</p><p className="leading-8 text-muted-foreground">يصف هذا البيان التزام مُلتقى بإمكانية الوصول وفقًا لقانون مساواة الحقوق للأشخاص ذوي الإعاقة.</p><div className="mt-10 space-y-8">{sections.map(({ he, ar }) => <section key={he[0]} className="grid gap-6 border-b border-border pb-8 md:grid-cols-2"><div dir="rtl"><h2 className="font-heading text-2xl font-semibold text-foreground">{he[0]}</h2><p className="mt-3 leading-8 text-muted-foreground">{he[1]}</p></div><div dir="rtl" className="border-t border-border pt-6 md:border-r md:border-t-0 md:pr-6 md:pt-0"><h2 className="font-heading text-2xl font-semibold text-foreground">{ar[0]}</h2><p className="mt-3 leading-8 text-muted-foreground">{ar[1]}</p></div></section>)}</div></article><SiteFooter /></main>;
}